routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Front'], function () {
    Route::get('/', 'PageController@index')->name('index');
    Route::get('/news', 'News\NewsController@index')->name('news');
    Route::get('/news/{news:slug}', 'News\NewsController@show')->name('news.show');
    Route::get('/search', 'Search\SearchController@search')->name('search');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');


    Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {

        Route::name('admin.')->group(function () {
            Route::resource('/news', 'News\NewsController');
            Route::resource('/articles', 'Articles\ArticleController');
            Route::resource('/albums', 'Albums\AlbumController');
            Route::resource('/videos', 'Videos\VideoController');
            Route::resource('/files', 'Files\FileController');
        });

    });
});

app/Models/Albums/Album.php
<?php

namespace App\Models\Albums;

use App\Models\BaseModel;
use Illuminate\Database\Eloquent\Model;

class Album extends BaseModel
{
    protected $fillable = [
        'title',
        'text',
        'image',
    ];

    public function photos()
    {
        return $this->hasMany(Photo::class);
    }
}

app/Models/Albums/Photo.php
<?php

namespace App\Models\Albums;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $fillable = [
      'album_id',
      'news_id',
      'image',
      'title'
    ];

    public function album()
    {
        return $this->belongsTo(Album::class);
    }

    public function news()
    {
        return $this->belongsTo(News::class);
    }
}

app/Http/Controllers/Admin/Albums/AlbumController.php
<?php

namespace App\Http\Controllers\Admin\Albums;

use App\Http\Controllers\Controller;
use App\Http\Requests\Album\StoreAlbumRequest;
use App\Models\Albums\Album;
use Illuminate\Http\Request;
use App\Services\Albums\AlbumService as Service;

class AlbumController extends Controller
{
    public function __construct()
    {
        $this->service = app(Service::class);
    }

    /**
     * @return mixed
     */
    public function create()
    {
        return $this->createElementModal();
    }


    /**
     * @param StoreAlbumRequest $request
     * @return mixed
     */
    public function store(StoreAlbumRequest $request)
    {
        return $this->storeElement($request->validated());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Album $album
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @internal param News $news
     * @internal param Task $task
     */
    public function edit(Album $album)
    {
        return $this->editElementModal($album);
    }

    /**
     * Show the resource.
     *
     * @param Album $album
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @internal param News $news
     * @internal param Task $task
     */
    public function show(Album $album)
    {
        return $this->showElementModal($album);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param StoreAlbumRequest|Request $request
     * @param Album $album
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     * @internal param News $news
     * @internal param Task $task
     */
    public function update(StoreAlbumRequest $request, Album $album)
    {
        return $this->updateElement($request->validated(), $album);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Album $album
     * @return \Illuminate\Http\JsonResponse
     * @internal param News $news
     * @internal param Task $task
     */
    public function destroy(Album $album)
    {
        return $this->destroyElement($album);
    }
}

resources/views/admin/albums/form.blade.php
<form id="create" method="POST" enctype="multipart/form-data" role="form">
    @csrf
    <div class="modal-body row">
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <label>Название<sup class="text-danger">*</sup></label>
                <input name="title" type="text" class="form-control" placeholder="Задача организации" required
                       @if (isset($album))
                       value="{{ $album->title }}"
                       @else
                       value="{{ old('title') }}"
                        @endif
                >
            </div>
            <div class="form-group">
                <label>Изображение альбома</label>
                <div class="custom-file">
                    <input class="custom-file-input" type="file" name="image"
                           id="validatedCustomFile" accept=".jpg,.jpeg,.png,.webp"
                           data-id="image"/>
                    <label class="custom-file-label" for="validatedCustomFile"
                           data-browse="Обзор">16:9</label>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <a id="image" class="fancybox"
                   @if ($method != 'create' and !is_null($album->image))
                   href="{{ asset('/storage' . $album->image) }}"
                   @else
                   href=""
                        @endif
                >
                    <img class="card-img-top "
                         @if ($method != 'create' and !is_null($album->image))
                         src="{{ asset('/storage' . $album->image) }}"
                         @else
                         src=""
                            @endif
                    >
                </a>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="form-group">
                <label>Текст альбома</label>
                <textarea name="text" id="summernote">
                   @if (isset($album))
                        {{ $album->text }}
                    @else
                        {{ old('text') }}
                    @endif
                </textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="form-group">
                <label>Фотографии альбома</label>
            </div>
            <hr>
        </div>

        @if($method == 'create')
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" data-id-step-block="0" data-name="step-block">
                <div class="row m-auto">
                    <div class="form-group mr-2">
                        <label>Заголовок</label>
                        <input name="photos[0][title]" type="text" class="form-control"
                               value="{{ old('photos.0.title') }}">
                    </div>
                    <div class="form-group mr-2">
                        <label>Фотография</label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input name="photos[0][image]" type="file" class="custom-file-input"
                                       id="validatedCustomFile" accept=".jpg,.jpeg,.png,.webp"
                                       value="{{ old('photos.0.image') }}" data-id="0">
                                <label class="custom-file-label rounded-right" for="validatedCustomFile"
                                       data-browse="Обзор">Загрузите фотографию</label>
                            </div>
                            <div class="input-group-append pl-2">
                                <button type="button" class="btn btn-light btn-icon rounded-sm mr-2"
                                        onclick="SiteControl.eventAddStep()">
                                    <i class="fas fa-plus"></i>
                                </button>
                                <button type="button" class="btn btn-danger btn-icon rounded-sm mr-2"
                                        onclick="SiteControl.eventDeleteStep(0)">
                                    <i class="fas fa-trash"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-xs-3 col-sm-3 col-md-2 col-lg-1">
                        <a id="0" class="fancybox" href="">
                            <img class="card-img-top" src="">
                        </a>
                    </div>
                </div>
            </div>
        @else
            @if(isset($album) && isset($album->photos))
                @foreach($album->photos as $photo)
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" data-id-step-block="{{$photo->id}}" data-name="step-block">
                        <div class="row m-auto">
                            <div class="form-group mr-2">
                                <label>Заголовок</label>
                                <input name="photos['{{$photo->id}}'][title]" type="text" class="form-control"
                                       value="{{ $photo->title }}">
                            </div>
                            <div class="form-group col-xs-3 col-sm-3 col-md-2 col-lg-1">
                                <a id="{{$photo->id}}" class="fancybox" href="{{ asset('/storage' . $photo->image) }}">
                                    <img class="card-img-top" src="{{ asset('/storage' . $photo->image) }}">
                                </a>
                            </div>
                            <div class="form-group mr-2">
                                <div class="input-group">
                                    {{--<input name="photos['{{$photo->id}}'][image]" type="text" value="{{ $photo->image }}">--}}
                                    <div class="input-group-append pl-2">
                                        <button type="button" class="btn btn-light btn-icon rounded-sm mr-2"
                                                onclick="SiteControl.eventAddStep()">
                                            <i class="fas fa-plus"></i>
                                        </button>
                                        {{--<button type="button" class="btn btn-danger btn-icon rounded-sm mr-2"--}}
                                                {{--onclick="SiteControl.eventDeleteStep({{$photo->id}})">--}}
                                            {{--<i class="fas fa-trash"></i>--}}
                                        {{--</button>--}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            @endif
        @endif
        <div data-name="after-step-block"></div>
    </div>
    <div class="modal-footer">
        <a href="javascript:void(0)" class="btn btn-success modal-button-form"
           @if(isset($album)) onclick="Main.updateRecord('{{ route('admin.albums.update', $album->id) }}')"
           @else onclick="Main.storeRecord('{{ route('admin.albums.store') }}')" @endif
        >Сохранить и добавить</a>
        <button type="button" class="btn btn-danger" onclick="Main.dissmissModal('#form')">Отмена</button>
    </div>
</form>

resources/views/admin/albums/index.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <div class="page-title">
        <h2 class="text-md text-highlight">{{ $title }}</h2>
    </div>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-3">
                            <button type="button" class="btn btn-success"
                                    onclick="Main.createRecord('{{ route('admin.albums.create') }}')">
                                {{ __('albums.create.title') }}
                            </button>
                        </div>
                        <div class="form-group col-xs-12 col-sm-12 col-md-5 col-lg-4">
                            <input type="text" class="form-control" placeholder="{{ __('albums.search.title') }}"
                                   onkeyup="Main.searchDataTable(dtListelements, this);"
                                   onchange="Main.searchDataTable(dtListelements, this);" data-name="filter">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-3">
                            <label>{{ __('albums.search.period') }}</label>
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                                    </div>
                                    <input class="form-control" name="period" data-name="filter"
                                           onchange="Main.updateDataTable(event, dtListelements);" daterangepicker
                                           placeholder="{{ __('albums.search.period') }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-xs-12 col-sm-12 col-md-5 col-lg-3 col-form-label text-right">
                            <br>
                            <button class="btn btn-primary"
                                    onclick="Main.dropFilter()">{{ __('albums.search.clear_filter') }}</button>
                        </div>
                    </div>
                </div>
                <div class="p-3">
                    <table style="width: 100%;" class="table table-theme table-row v-middle table-text" id="listelement-table">
                        <thead>
                        @if(!empty($columns))
                            <tr>
                                @foreach ($columns as $column)
                                    <th>{{ $column['column_name'] }}</th>
                                @endforeach
                            </tr>
                        @endif
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script>
        let dtListelements = $('#listelement-table').DataTable(Object.assign({
            ajax: {
                url: "{{ route('admin.albums.index') }}",
                data: function (d) {
                    d.period = $('input[name=period]').val();
                },
                error: function (data) {
                    toastr.error('Ошибка загрузки данных для таблицы. Пожалуйста, перезагрузите страницу');
                },
            },
            columns: {!! $jsonColumns !!},
            sDom: '<"top">rt<"bottom"p><"clear">',
        }, Main.commonConfigDt));

        dtListelements.on('draw', function () {
            Main.showModalElementDataTable('listelement-table');
        });
    </script>
@endsection