routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Front'], function () {
    Route::get('/', 'PageController@index')->name('index');
    Route::get('/news', 'News\NewsController@index')->name('news');
    Route::get('/news/{news:slug}', 'News\NewsController@show')->name('news.show');
    Route::get('/search', 'Search\SearchController@search')->name('search');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');


    Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {

        Route::name('admin.')->group(function () {
            Route::resource('/news', 'News\NewsController');
            Route::resource('/articles', 'Articles\ArticleController');
            Route::resource('/albums', 'Albums\AlbumController');
            Route::resource('/videos', 'Videos\VideoController');
            Route::resource('/files', 'Files\FileController');
        });

    });
});

app/Models/Videos/Video.php
<?php

namespace App\Models\Videos;

use App\Models\BaseModel;

class Video extends BaseModel
{
    protected $fillable = [
        'slug',
        'title',
        'description',
        'alt_image',
        'title_image',
        'image',
        'video',
        'text',
        'text_preview',
        'views',
        'is_published',
        'article_subcategory_id',
        'user_id',
        'published_at'
    ];

    protected $casts = [
        'is_published' => 'boolean'
    ];

    protected $dates = [
        'published_at',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function scopePublished($query)
    {
        return $query->where('is_published', 1)->orderBy('published_at', 'desc');
    }

    public function setVideoAttribute($value)
    {
        if (isset($value)) {
            parse_str( parse_url( $value, PHP_URL_QUERY ), $parsedArray );
            if (isset($parsedArray['v'])) {
                $this->attributes['video'] = 'https://www.youtube.com/embed/'.$parsedArray['v'];
            }
        }
    }
}

app/Http/Controllers/Admin/Videos/VideoController.php
<?php

namespace App\Http\Controllers\Admin\Videos;

use App\Http\Controllers\Controller;
use App\Http\Requests\Video\StoreVideoRequest;
use App\Models\Videos\Video;
use App\Services\Videos\VideoService as Service;


class VideoController extends Controller
{
    public function __construct()
    {
        $this->service = app(Service::class);
    }

    /**
     * @return mixed
     */
    public function create()
    {
        return $this->createElementModal();
    }


    /**
     * @param StoreVideoRequest $request
     * @return mixed
     */
    public function store(StoreVideoRequest $request)
    {
        return $this->storeElement($request->validated());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Video $video
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @internal param News $news
     * @internal param Task $task
     */
    public function edit(Video $video)
    {
        return $this->editElementModal($video);
    }

    /**
     * Show the resource.
     *
     * @param Video $video
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @internal param News $news
     * @internal param Task $task
     */
    public function show(Video $video)
    {
        return $this->showElementModal($video);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param StoreVideoRequest $request
     * @param Video $video
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     * @internal param News $news
     * @internal param Task $task
     */
    public function update(StoreVideoRequest $request, Video $video)
    {
        return $this->updateElement($request->validated(), $video);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Video $video
     * @return \Illuminate\Http\JsonResponse
     * @internal param News $news
     * @internal param Task $task
     */
    public function destroy(Video $video)
    {
        return $this->destroyElement($video);
    }
}

resources/views/admin/videos/form.blade.php
<form id="create" method="POST" enctype="multipart/form-data" role="form">
    @csrf
    <div class="modal-body row">
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <label>Название<sup class="text-danger">*</sup></label>
                <input name="title" type="text" class="form-control" placeholder="Задача организации" required
                       @if (isset($video))
                       value="{{ $video->title }}"
                       @else
                       value="{{ old('title') }}"
                        @endif
                >
            </div>
            <div class="form-group">
                <label>Description</label>
                <input name="description" type="text" class="form-control" placeholder="Задача организации"
                       @if (isset($video))
                       value="{{ $video->description }}"
                       @else
                       value="{{ old('description') }}"
                        @endif
                >
            </div>
            <div class="form-group">
                <label>Ссылка на видео Youtube</label>
                <input name="video" type="text" class="form-control" placeholder="https://www.youtube.com/watch?v=JthbuxKuIy8"
                       @if (isset($video))
                       value="{{ $video->video }}"
                       @else
                       value="{{ old('video') }}"
                        @endif
                >
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 row">
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 ">
                    <div class="form-group">
                        <label>Изображение видео</label>
                        <div class="custom-file">
                            <input class="custom-file-input" type="file" name="image"
                                   id="validatedCustomFile" accept=".jpg,.jpeg,.png,.webp"
                                   data-id="image"/>
                            <label class="custom-file-label" for="validatedCustomFile"
                                   data-browse="Обзор">16:9</label>
                        </div>
                        <input type="hidden" name="selection_x">
                        <input type="hidden" name="selection_y">
                        <input type="hidden" name="selection_width">
                        <input type="hidden" name="selection_height">
                    </div>
                    <div class="form-group">
                        <label>Title-текст изображения</label>
                        <input name="title_image" type="text" class="form-control" placeholder="Управляющая компания"
                               @if (isset($video))
                               value="{{ $video->title_image }}"
                               @else
                               value="{{ old('title_image') }}"
                                @endif
                        >
                    </div>
                    <div class="form-group">
                        <label>Alt-текст изображения</label>
                        <input name="alt_image" type="text" class="form-control" placeholder="Дом"
                               @if (isset($video))
                               value="{{ $video->alt_image }}"
                               @else
                               value="{{ old('alt_image') }}"
                                @endif
                        >
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6  align-self-center d-flex justify-content-center">
                    <div class="col-xs-12 col-sm-11 col-md-11 col-lg-11" >
                        <div class="form-group">
                            <a id="image" class="fancybox"
                               @if ($method != 'create' and !is_null($video->image))
                               href="{{ asset('/storage' . $video->image) }}"
                               @else
                               href=""
                                @endif
                            >
                                <img class="card-img-top "
                                     @if ($method != 'create' and !is_null($video->image))
                                     src="{{ asset('/storage' . $video->image) }}"
                                     @else
                                     src=""
                                        @endif
                                >
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="form-group">
                <div id="some_container_div"></div>
            </div>
            <div class="form-group">
                <label>Превью текст видео</label>
                <textarea name="text_preview" id="summernote">
                   @if (isset($video))
                        {{ $video->text_preview }}
                    @else
                        {{ old('text_preview') }}
                    @endif
                </textarea>
            </div>
            <div class="form-group">
                <label>Текст видео<sup class="text-danger">*</sup></label>
                <textarea name="text" id="summernote2" required>
                   @if (isset($video))
                    {{ $video->text }}
                    @else
                        {{ old('text') }}
                    @endif
                </textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="form-group row">
                <div class="col-xs-5 col-sm-5 col-md-3 col-lg-3">
                    <label>Дата и время размещения<sup class="text-danger">*</sup></label>
                    <input name="published_at" type="text" class="form-control" required
                           data-timeinputmask
                           data-position="right bottom"
                           datepicker
                           data-date-format="dd.mm.yyyy hh:ii"
                           data-timepicker="true"
                           placeholder="02.06.2020 16:24"
                           @if (isset($video))
                           value="{{ $video->published_at->format('d.m.Y H:i') }}"
                           @else
                           value="{{ Carbon\Carbon::now()->format('d.m.Y H:i') }}"
                           @endif
                    >
                </div>
                <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                    <label>URL<span class="text-danger">*Не обязательно для заполнения</span></label>
                    <input name="slug" type="text" class="form-control" placeholder="kommunalnyye-uslugi"
                           @if (isset($video))
                           value="{{ $video->slug }}"
                           @else
                           value="{{ old('slug') }}"
                            @endif
                    >
                </div>
                <div class="col-xs-5 col-sm-5 col-md-3 col-lg-3 mt-1">
                    <div class="custom-control custom-switch align-self-center">
                        <input name="is_published"  type="hidden" class="custom-control-input" value="0" >
                        <input name="is_published"  type="checkbox" class="custom-control-input" value="1" id="ispublish" @if(isset($video) and $video->is_published == 1) checked @endif>
                        <label class="custom-control-label" for="ispublish">Опубликовано</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a href="javascript:void(0)" class="btn btn-success modal-button-form"
           @if(isset($video)) onclick="Main.updateRecord('{{ route('admin.videos.update', $video->id) }}')"
           @else onclick="Main.storeRecord('{{ route('admin.videos.store') }}')" @endif
        >Сохранить и добавить</a>
        <button type="button" class="btn btn-danger" onclick="Main.dissmissModal('#form')">Отмена</button>
    </div>
</form>

resources/views/admin/videos/index.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <div class="page-title">
        <h2 class="text-md text-highlight">{{ $title }}</h2>
    </div>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-3">
                            <button type="button" class="btn btn-success"
                                    onclick="Main.createRecord('{{ route('admin.videos.create') }}')">
                                {{ __('videos.create.title') }}
                            </button>
                        </div>
                        <div class="form-group col-xs-12 col-sm-12 col-md-5 col-lg-4">
                            <input type="text" class="form-control" placeholder="{{ __('videos.search.title') }}"
                                   onkeyup="Main.searchDataTable(dtListelements, this);"
                                   onchange="Main.searchDataTable(dtListelements, this);" data-name="filter">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-3">
                            <label>{{ __('videos.search.period') }}</label>
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                                    </div>
                                    <input class="form-control" name="period" data-name="filter"
                                           onchange="Main.updateDataTable(event, dtListelements);" daterangepicker
                                           placeholder="{{ __('videos.search.period') }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-xs-12 col-sm-12 col-md-5 col-lg-3 col-form-label text-right">
                            <br>
                            <button class="btn btn-primary"
                                    onclick="Main.dropFilter()">{{ __('videos.search.clear_filter') }}</button>
                        </div>
                    </div>
                </div>
                <div class="p-3">
                    <table style="width: 100%;" class="table table-theme table-row v-middle table-text" id="listelement-table">
                        <thead>
                        @if(!empty($columns))
                            <tr>
                                @foreach ($columns as $column)
                                    <th>{{ $column['column_name'] }}</th>
                                @endforeach
                            </tr>
                        @endif
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script>
        let dtListelements = $('#listelement-table').DataTable(Object.assign({
            ajax: {
                url: "{{ route('admin.videos.index') }}",
                data: function (d) {
                    d.period = $('input[name=period]').val();
                },
                error: function (data) {
                    toastr.error('Ошибка загрузки данных для таблицы. Пожалуйста, перезагрузите страницу');
                },
            },
            columns: {!! $jsonColumns !!},
            sDom: '<"top">rt<"bottom"p><"clear">',
        }, Main.commonConfigDt));

        dtListelements.on('draw', function () {
            Main.showModalElementDataTable('listelement-table');
        });
    </script>
@endsection