routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Front'], function () {
    Route::get('/', 'PageController@index')->name('index');
    Route::get('/news', 'News\NewsController@index')->name('news');
    Route::get('/news/{news:slug}', 'News\NewsController@show')->name('news.show');
    Route::get('/search', 'Search\SearchController@search')->name('search');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');


    Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {

        Route::name('admin.')->group(function () {
            Route::resource('/news', 'News\NewsController');
            Route::resource('/articles', 'Articles\ArticleController');
            Route::resource('/albums', 'Albums\AlbumController');
            Route::resource('/videos', 'Videos\VideoController');
            Route::resource('/files', 'Files\FileController');
        });

    });
});

resources/views/admin/documents/form.blade.php
<form id="create" method="POST" enctype="multipart/form-data" role="form">
    @csrf
    <div class="modal-body row">
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <label>Название документа<sup class="text-danger">*</sup></label>
                <input name="title" type="text" class="form-control" placeholder="Задача организации" required
                       @if (isset($file))
                       value="{{ $file->title }}"
                       @else
                       value="{{ old('title') }}"
                        @endif
                >
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <label>Файл</label>
                <div class="custom-file">
                    <input class="custom-file-input" type="file" name="file"/>
                    <label class="custom-file-label" for="validatedCustomFile"
                           data-browse="Обзор">Загрузите документ</label>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a href="javascript:void(0)" class="btn btn-success modal-button-form"
           @if(isset($file)) onclick="Main.updateRecord('{{ route('admin.files.update', $file->id) }}')"
           @else onclick="Main.storeRecord('{{ route('admin.files.store') }}')" @endif
        >Сохранить и добавить</a>
        <button type="button" class="btn btn-danger" onclick="Main.dissmissModal('#form')">Отмена</button>
    </div>
</form>

resources/views/admin/documents/index.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <div class="page-title">
        <h2 class="text-md text-highlight">{{ $title }}</h2>
    </div>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-3">
                            <button type="button" class="btn btn-success"
                                    onclick="Main.createRecord('{{ route('admin.files.create') }}')">
                                {{ __('files.create.title') }}
                            </button>
                        </div>
                        <div class="form-group col-xs-12 col-sm-12 col-md-5 col-lg-4">
                            <input type="text" class="form-control" placeholder="{{ __('files.search.title') }}"
                                   onkeyup="Main.searchDataTable(dtListelements, this);"
                                   onchange="Main.searchDataTable(dtListelements, this);" data-name="filter">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-3">
                            <label>{{ __('files.search.period') }}</label>
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                                    </div>
                                    <input class="form-control" name="period" data-name="filter"
                                           onchange="Main.updateDataTable(event, dtListelements);" daterangepicker
                                           placeholder="{{ __('files.search.period') }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-xs-12 col-sm-12 col-md-5 col-lg-3 col-form-label text-right">
                            <br>
                            <button class="btn btn-primary"
                                    onclick="Main.dropFilter()">{{ __('files.search.clear_filter') }}</button>
                        </div>
                    </div>
                </div>
                <div class="p-3">
                    <table style="width: 100%;" class="table table-theme table-row v-middle table-text" id="listelement-table">
                        <thead>
                        @if(!empty($columns))
                            <tr>
                                @foreach ($columns as $column)
                                    <th>{{ $column['column_name'] }}</th>
                                @endforeach
                            </tr>
                        @endif
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script>
        let dtListelements = $('#listelement-table').DataTable(Object.assign({
            ajax: {
                url: "{{ route('admin.files.index') }}",
                data: function (d) {
                    d.period = $('input[name=period]').val();
                },
                error: function (data) {
                    toastr.error('Ошибка загрузки данных для таблицы. Пожалуйста, перезагрузите страницу');
                },
            },
            columns: {!! $jsonColumns !!},
            sDom: '<"top">rt<"bottom"p><"clear">',
        }, Main.commonConfigDt));
    </script>
@endsection